### ISSUE TITLE
Cordova build failure

### ISSUE THREAD

**Issue by tweakitguy** [happydenn/cordova-plugin-gimbal2#3]
Not sure if this was ever tested with meteor at all.  But receiving a build failure issue when trying to build the xcode project for distribution/testing.

I've reset my project, removed and re-added the platform and deleted all previous builds.  Any suggestions?   If I do remove this package the build does work.

 Appreciate the help.

```
=> Errors executing Cordova commands:                                              

   While building Cordova app for platform iOS:
   Error: /Users/brentpatroch/Documents/dev/astralbeacon/astral-beacon/.meteor/local/cordova-build/platforms/ios/cordova/build: Command failed with exit code 2 Error output:
   ** BUILD FAILED **


   The following build commands failed:
   CompileC build/Astral\ Beacon.build/Release-iphonesimulator/Astral\ Beacon.build/Objects-normal/i386/Gimbal2.o Astral\ Beacon/Plugins/io.hpd.cordova.gimbal2/Gimbal2.m normal i386 objective-c
   com.apple.compilers.llvm.clang.1_0.compiler
   (1 failure)
   Error code 65 for command: xcodebuild with args:
   -xcconfig,/Users/brentpatroch/Documents/dev/astralbeacon/astral-beacon/.meteor/local/cordova-build/platforms/ios/cordova/build-release.xcconfig,-project,Astral Beacon.xcodeproj,ARCHS=i386,-target,Astral
   Beacon,-configuration,Release,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/brentpatroch/Documents/dev/astralbeacon/astral-beacon/.meteor/local/cordova-build/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/brentpatroch/Documents/dev/astralbeacon/astral-beacon/.meteor/local/cordova-build/platforms/ios/build/sharedpch
   at ChildProcess.whenDone
   (/Users/brentpatroch/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
   at ChildProcess.emit (events.js:98:17)
   at maybeClose (child_process.js:766:16)
   at Socket.<anonymous> (child_process.js:979:11)
   at Socket.emit (events.js:95:17)
   at Pipe.close (net.js:466:12)
```

**Comment by ennea8** [comment]
Encounter similar problem

```
=> Errors executing Cordova commands:                                              
                                              
   While building Cordova app for platform iOS:
   Error: /Users/fanjinhui/Desktop/cordova-plugins/test/.meteor/local/cordova-build/platforms/ios/cordova/build: Command failed with exit code 2 Error
   output:
   ** BUILD FAILED **
   
   
   The following build commands failed:
   CompileC build/meteor_ihealth_plugin.build/Release-iphonesimulator/meteor_ihealth_plugin.build/Objects-normal/i386/AmManagerCordova.o
   meteor_ihealth_plugin/Plugins/com.ihealth.plugin.am.ammanagercordova/AmManagerCordova.m normal i386 objective-c
   com.apple.compilers.llvm.clang.1_0.compiler
   (1 failure)
   Error code 65 for command: xcodebuild with args:
   -xcconfig,/Users/fanjinhui/Desktop/cordova-plugins/test/.meteor/local/cordova-build/platforms/ios/cordova/build-release.xcconfig,-project,meteor_ihealth_plugin.xcodeproj,ARCHS=i386,-target,meteor_ihealth_plugin,-configuration,Release,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/fanjinhui/Desktop/cordova-plugins/test/.meteor/local/cordova-build/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/fanjinhui/Desktop/cordova-plugins/test/.meteor/local/cordova-build/platforms/ios/build/sharedpch
   at ChildProcess.whenDone
   (/Users/fanjinhui/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
   at ChildProcess.emit (events.js:98:17)
   at maybeClose (child_process.js:766:16)
   at Socket.<anonymous> (child_process.js:979:11)
   at Socket.emit (events.js:95:17)
   at Pipe.close (net.js:466:12)

```

**Comment by tweakitguy** [comment]
Found best option was to use `meteor run ios-device` instead of build, this will directly launch xcode, from which you can archive or run on device.

**Comment by happydenn** [comment]
@tweakitguy Sorry been a bit busy and didn't notice this thread. I'm not too familiar with Meteor and Cordova but I'm glad that you could find a way to make things work together. And thanks for reporting back too!
